[2024-05-25T06:35:19.814+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T06:35:19.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_and_deploy_model.manage_models manual__2024-05-25T06:35:16.369596+00:00 [queued]>
[2024-05-25T06:35:19.825+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_and_deploy_model.manage_models manual__2024-05-25T06:35:16.369596+00:00 [queued]>
[2024-05-25T06:35:19.825+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-25T06:35:19.829+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): manage_models> on 2024-05-25 06:35:16.369596+00:00
[2024-05-25T06:35:19.831+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T06:35:19.832+0000] {standard_task_runner.py:63} INFO - Started process 86 to run task
[2024-05-25T06:35:19.832+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_and_deploy_model', 'manage_models', 'manual__2024-05-25T06:35:16.369596+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/train_and_deploy_dag.py', '--cfg-path', '/tmp/tmpm6_k4g7i']
[2024-05-25T06:35:19.833+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask manage_models
[2024-05-25T06:35:19.848+0000] {task_command.py:426} INFO - Running <TaskInstance: train_and_deploy_model.manage_models manual__2024-05-25T06:35:16.369596+00:00 [running]> on host 130ac991300e
[2024-05-25T06:35:19.874+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_and_deploy_model' AIRFLOW_CTX_TASK_ID='manage_models' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T06:35:16.369596+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T06:35:16.369596+00:00'
[2024-05-25T06:35:19.875+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T06:35:19.885+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-05-25T06:35:19.932+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-25T06:35:19.932+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T06:35:19.936+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=train_and_deploy_model, task_id=manage_models, run_id=manual__2024-05-25T06:35:16.369596+00:00, execution_date=20240525T063516, start_date=20240525T063519, end_date=20240525T063519
[2024-05-25T06:35:19.980+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T06:35:19.987+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T06:35:19.987+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
